// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LoggerfDataProvider is an autogenerated mock type for the LoggerfDataProvider type
type LoggerfDataProvider struct {
	mock.Mock
}

// GetFields provides a mock function with given fields:
func (_m *LoggerfDataProvider) GetFields() map[string]interface{} {
	ret := _m.Called()

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// GetInfo provides a mock function with given fields:
func (_m *LoggerfDataProvider) GetInfo() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewLoggerfDataProvider interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoggerfDataProvider creates a new instance of LoggerfDataProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoggerfDataProvider(t mockConstructorTestingTNewLoggerfDataProvider) *LoggerfDataProvider {
	mock := &LoggerfDataProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
