// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	util "go-template/share/general/util"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Errorf provides a mock function with given fields: ldp
func (_m *Logger) Errorf(ldp util.LoggerfDataProvider) {
	_m.Called(ldp)
}

// Infof provides a mock function with given fields: ldp
func (_m *Logger) Infof(ldp util.LoggerfDataProvider) {
	_m.Called(ldp)
}

type mockConstructorTestingTNewLogger interface {
	mock.TestingT
	Cleanup(func())
}

// NewLogger creates a new instance of Logger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLogger(t mockConstructorTestingTNewLogger) *Logger {
	mock := &Logger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
