// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RandomTokenGenerator is an autogenerated mock type for the RandomTokenGenerator type
type RandomTokenGenerator struct {
	mock.Mock
}

// Generate provides a mock function with given fields: tokenNumber
func (_m *RandomTokenGenerator) Generate(tokenNumber int) (string, error) {
	ret := _m.Called(tokenNumber)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(tokenNumber)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(tokenNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewRandomTokenGenerator interface {
	mock.TestingT
	Cleanup(func())
}

// NewRandomTokenGenerator creates a new instance of RandomTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRandomTokenGenerator(t mockConstructorTestingTNewRandomTokenGenerator) *RandomTokenGenerator {
	mock := &RandomTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
